export const DEFAULT_SWIMMING_SESSION_TITLE = 'Pool session'
export const DEFAULT_GYM_SESSION_TITLE = 'Gym session'
export const DEFAULT_SESSION_BLOCK_TITLE = 'Block'
export const LEGACY_FLAT_BLOCK_TITLE = 'Session'

export const NEW_SWIM_BLOCK_DEFAULT_EXPLICIT_METERS = 400
export const NEW_SWIM_BLOCK_DEFAULT_DURATION_SECONDS = 600
export const NEW_GYM_BLOCK_DEFAULT_DURATION_SECONDS = 1800
