import { ATHLETE_GROUP_MAX_LENGTH } from '@/shared/constants/athleteGroup.constants'
import {
  GYM_DURATION,
  WORKOUT_DURATION,
  WORKOUT_NOTES,
} from '@/shared/constants/workoutValidation.constants'

export const SESSION_PERSISTENCE_FIELD_LIMITS = {
  SESSION_TITLE_MAX_LENGTH: 200,
  BLOCK_TITLE_MAX_LENGTH: 200,
  SWIM_REPETITIONS_MAX: 10_000,
  INTERVAL_SENDOFF_MAX_SECONDS: 86_400,
} as const

export const SWIM_SESSION_DURATION_SECONDS_MAX = WORKOUT_DURATION.MAX_MINUTES * 60
export const GYM_SESSION_DURATION_SECONDS_MAX = GYM_DURATION.MAX_MINUTES * 60

export const WORKOUT_TEMPLATE_FIELD_LIMITS = {
  TITLE_MAX_LENGTH: 200,
  TITLE_MIN_TRIM_LENGTH: 1,
  TARGET_GROUP_MAX_LENGTH: ATHLETE_GROUP_MAX_LENGTH,
  DESCRIPTION_MAX_LENGTH: WORKOUT_NOTES.MAX_LENGTH,
  TAG_MAX_LENGTH: 48,
  TAGS_MAX_COUNT: 24,
} as const
